spring.application.name=auth-service
server.port=9510

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# JWT
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation12345678901234567890
jwt.expiration=86400000

spring.profiles.active=jwt

# ????????? ???????????
logging.level.root=INFO
logging.level.by.step=DEBUG
logging.level.by.step.config=DEBUG
logging.level.by.step.controller=DEBUG
logging.level.by.step.service=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n
logging.file.name=logs/auth-service.log
logging.file.max-size=10MB
logging.file.max-history=30